export function renderProvisionSql(manifest, now = Date.now()) {
  if (!Number.isSafeInteger(now) || now <= 0) throw new Error('now must be a positive integer');
  const header = [
    '-- Generated by tools/cf-webmail.mjs. Review before applying.',
    'PRAGMA foreign_keys = ON;',
  ];
  const guards = renderOwnershipGuards(manifest);
  const statements = [];
  for (const user of manifest.users) {
    statements.push(sql(`
      INSERT INTO users (id, email, display_name, status, created_at, updated_at)
      VALUES (${q(user.id)}, ${q(user.email)}, ${nullable(user.displayName)}, 'active', ${now}, ${now})
      ON CONFLICT(id) DO UPDATE SET
        email = excluded.email,
        display_name = excluded.display_name,
        status = 'active',
        updated_at = excluded.updated_at
    `));
    if (user.systemAdmin) {
      statements.push(sql(`
        INSERT INTO system_administrators (user_id, granted_by_user_id, source, granted_at)
        VALUES (${q(user.id)}, ${q(user.id)}, 'provisioning', ${now})
        ON CONFLICT(user_id) DO UPDATE SET
          source = 'provisioning',
          granted_at = excluded.granted_at
      `));
    }
    for (const identity of user.identities) {
      statements.push(sql(`
        INSERT INTO access_identities (
          issuer, subject, user_id, email, created_at, updated_at, last_seen_at
        ) VALUES (
          ${q(identity.issuer)}, ${q(identity.subject)}, ${q(user.id)},
          ${q(identity.email)}, ${now}, ${now}, ${now}
        )
        ON CONFLICT(issuer, subject) DO UPDATE SET
          email = excluded.email,
          updated_at = excluded.updated_at,
          last_seen_at = MAX(access_identities.last_seen_at, excluded.last_seen_at)
      `));
    }
  }
  for (const mailbox of manifest.mailboxes) {
    statements.push(sql(`
      INSERT INTO mailboxes (id, display_name, status, created_at, updated_at)
      VALUES (${q(mailbox.id)}, ${q(mailbox.displayName)}, 'active', ${now}, ${now})
      ON CONFLICT(id) DO UPDATE SET
        display_name = excluded.display_name,
        status = 'active',
        updated_at = excluded.updated_at
    `));
    statements.push(addressSql(mailbox.address, mailbox.id, 'primary', now));
    for (const alias of mailbox.aliases) statements.push(addressSql(alias, mailbox.id, 'alias', now));
    statements.push(membershipSql(mailbox.id, mailbox.ownerUserId, 'owner', now));
    for (const member of mailbox.members) {
      statements.push(membershipSql(mailbox.id, member.userId, member.role, now));
    }
  }
  return `${[...header, ...guards, ...statements].join('\n\n')}\n`;
}

export function renderRetryOutboundSql(messageId, now = Date.now()) {
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(messageId)) {
    throw new Error('message ID must be a UUID');
  }
  if (!Number.isSafeInteger(now) || now <= 0) throw new Error('now must be a positive integer');
  return [
    sql(`
      UPDATE outbound_deliveries
      SET status = 'queued', attempt_count = 0, enqueued_at = 1,
        next_attempt_at = ${now}, lease_expires_at = 0, lease_token = '',
        last_error_code = '', last_error_message = '', updated_at = ${now}
      WHERE message_id = ${q(messageId.toLowerCase())} AND status = 'failed'
    `),
    sql(`
      UPDATE messages
      SET status = 'queued', processing_error = '', updated_at = ${now}
      WHERE id = ${q(messageId.toLowerCase())} AND direction = 'outbound'
        AND EXISTS (
          SELECT 1 FROM outbound_deliveries
          WHERE message_id = ${q(messageId.toLowerCase())} AND status = 'queued'
        )
    `),
  ].join('\n\n') + '\n';
}

export function renderRetryDeadLetterSql(deadLetterId, now = Date.now()) {
  const id = deadLetterId.toLowerCase();
  if (!/^[0-9a-f]{64}$/u.test(id)) throw new Error('dead-letter ID must be a SHA-256 digest');
  if (!Number.isSafeInteger(now) || now <= 0) throw new Error('now must be a positive integer');
  return sql(`
    UPDATE queue_dead_letters
    SET status = 'retry_requested', retry_requested_at = ${now}, last_error = ''
    WHERE id = ${q(id)} AND status = 'pending' AND payload_valid = 1
  `) + '\n';
}

function addressSql(address, mailboxId, kind, now) {
  return sql(`
    INSERT INTO mailbox_addresses (
      address, mailbox_id, kind, status, created_at, updated_at
    ) VALUES (${q(address)}, ${q(mailboxId)}, ${q(kind)}, 'active', ${now}, ${now})
    ON CONFLICT(address) DO UPDATE SET
      status = 'active',
      updated_at = excluded.updated_at
  `);
}

function membershipSql(mailboxId, userId, role, now) {
  return sql(`
    INSERT INTO mailbox_memberships (
      mailbox_id, user_id, role, created_at, updated_at
    ) VALUES (${q(mailboxId)}, ${q(userId)}, ${q(role)}, ${now}, ${now})
    ON CONFLICT(mailbox_id, user_id) DO UPDATE SET
      role = excluded.role,
      updated_at = excluded.updated_at
  `);
}

function renderOwnershipGuards(manifest) {
  const guards = [];
  for (const user of manifest.users) {
    guards.push(guardSql(`
      EXISTS (
        SELECT 1 FROM users
        WHERE email = ${q(user.email)} COLLATE NOCASE AND id <> ${q(user.id)}
      )
    `));
    for (const identity of user.identities) {
      guards.push(guardSql(`
        EXISTS (
          SELECT 1 FROM access_identities
          WHERE issuer = ${q(identity.issuer)} AND subject = ${q(identity.subject)}
            AND user_id <> ${q(user.id)}
        )
      `));
    }
  }
  for (const mailbox of manifest.mailboxes) {
    for (const [address, kind] of [
      [mailbox.address, 'primary'],
      ...mailbox.aliases.map((alias) => [alias, 'alias']),
    ]) {
      guards.push(guardSql(`
        EXISTS (
          SELECT 1 FROM mailbox_addresses
          WHERE address = ${q(address)} COLLATE NOCASE
            AND (mailbox_id <> ${q(mailbox.id)} OR kind <> ${q(kind)})
        )
      `));
    }
  }
  return guards;
}

function guardSql(conflictExpression) {
  return sql(`
    SELECT CASE
      WHEN ${conflictExpression.trim()}
      THEN json_extract('CF_WEBMAIL_OWNERSHIP_CONFLICT', '$')
      ELSE 1
    END AS ownership_guard
  `);
}

function q(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

function nullable(value) {
  return value === undefined ? 'NULL' : q(value);
}

function sql(value) {
  return `${value.trim().replace(/^ {6}/gmu, '')};`;
}
