/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/web/wrangler.jsonc --include-runtime=false --env-interface=WebEnv apps/web/worker-configuration.d.ts` (hash: b5ba54c980d90afa8171cdb40b13ef76)
interface __BaseEnv_WebEnv {
	RAW_EMAILS: R2Bucket;
	DB: D1Database;
	OUTBOUND_QUEUE: Queue;
	ASSETS: Fetcher;
	ACCESS_TEAM_DOMAIN: "https://REPLACE_WITH_TEAM.cloudflareaccess.com";
	ACCESS_AUD: "REPLACE_WITH_ACCESS_AUD";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_WebEnv {}
}
interface WebEnv extends __BaseEnv_WebEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD">> {}
}
