/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/web/wrangler.jsonc --include-runtime=false apps/web/worker-configuration.d.ts` (hash: 91f9f7ae29775be4054da3e711bae6e1)
interface __BaseEnv_Env {
	RAW_EMAILS: R2Bucket;
	DB: D1Database;
	ACCESS_TEAM_DOMAIN: "https://REPLACE_WITH_TEAM.cloudflareaccess.com";
	ACCESS_AUD: "REPLACE_WITH_ACCESS_AUD";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD">> {}
}
