/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/ingest/wrangler.jsonc --include-runtime=false --env-interface=IngestEnv apps/ingest/worker-configuration.d.ts` (hash: 5cbb51b6af7460e678ecb0c066fc77c7)
interface __BaseEnv_IngestEnv {
	RAW_EMAILS: R2Bucket;
	DB: D1Database;
	INBOUND_QUEUE: Queue;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_IngestEnv {}
}
interface IngestEnv extends __BaseEnv_IngestEnv {}
