/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/ingest/wrangler.jsonc --include-runtime=false apps/ingest/worker-configuration.d.ts` (hash: 93f4ecdd14b8411df56baa6356a2f770)
interface __BaseEnv_Env {
	RAW_EMAILS: R2Bucket;
	DB: D1Database;
	INBOUND_QUEUE: Queue;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
