/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/jobs/wrangler.jsonc --include-runtime=false --env-interface=JobsEnv apps/jobs/worker-configuration.d.ts` (hash: 451a3faa842b6175913871b83022718f)
interface __BaseEnv_JobsEnv {
	RAW_EMAILS: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	INBOUND_QUEUE: Queue;
	OUTBOUND_QUEUE: Queue;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_JobsEnv {}
}
interface JobsEnv extends __BaseEnv_JobsEnv {}
