/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/jobs/wrangler.jsonc --include-runtime=false apps/jobs/worker-configuration.d.ts` (hash: df6854121331dfad67bb79bbed4d523d)
interface __BaseEnv_Env {
	RAW_EMAILS: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	INBOUND_QUEUE: Queue;
	OUTBOUND_QUEUE: Queue;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
